[package]
name = "memento"
version = "0.0.1"
authors = [ "rob thijssen <rthijssen@gmail.com>" ]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
github-rs = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"